[package]
name = "run-packet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
bytes = "1"
smoltcp = "0.8"

[dev-dependencies]
smoltcp = "0.8"
pnet = "0.31.0"